[package]
name = "rust-soccer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_rapier2d = "0.26.0"
blobs = "0.2.1"
uuid = "1.10.0"
